app/blueprints/products/models.py
from app import db

# Manages all the products
class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    desc = db.Column(db.String(250), nullable=False)
    price = db.Column(db.Numeric(10, 2), nullable=False)
    sm_image_url = db.Column(db.String(250), nullable=False)
    lg_image_url = db.Column(db.String(250), nullable=False)

    def __init__(self, name, desc, price, sm_image_url, lg_image_url,):
        self.name = name
        self.desc = desc
        self.price = price
        self.sm_image_url = sm_image_url
        self.lg_image_url = lg_image_url

# Join table the manages the relationship between an individual user and an individual product
# qty is currently set with 1 via the Add to Cart button on the Product page.  Future implementation 
# for Javascript
class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_id = db.Column(db.Integer, db.ForeignKey(
        'product.id'), nullable=False)
    qty = db.Column(db.Integer, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __init__(self, product_id, qty, user_id):
        self.product_id = product_id
        self.qty = qty
        self.user_id = user_id

app/blueprints/products/forms.py
from flask.app import Flask
from wtforms import SubmitField
from flask_wtf import FlaskForm

# Empty form provided to enable CSRF protection on product info page
class AddToCartForm(FlaskForm):
    submit = SubmitField()

# Empty form provided to enable CSRF protection on cart page
class CartForm(FlaskForm):
    remove_item = SubmitField()
    clear_cart = SubmitField()
    check_out = SubmitField()

app/blueprints/products/__init__.py
from flask import Blueprint

bp = Blueprint('products', __name__)

from . import routes, models

app/blueprints/products/routes.py
from app.blueprints.products.forms import AddToCartForm
from app import db
from flask import current_app as app
from flask.helpers import url_for
from werkzeug.utils import redirect
from . import bp as products
from flask import render_template, flash
from .models import Product, Cart
from flask_login import current_user, login_required
from .forms import AddToCartForm, CartForm
import stripe

##################################################################
############### PRODUCT INFORMATION PAGE  ########################
##################################################################


@products.route('/products/<int:product_id>')
def show_product(product_id):
    product = Product.query.get_or_404(product_id)
    form = AddToCartForm()
    cart_empty = is_empty()
    return render_template('product_view.html', product=product, form=form, cart_empty=cart_empty)

##################################################################
############### ADD TO CART ######################################
##################################################################

# Page is not displayed, this route adds an item to the cart and redirects to the index


@products.route('/products/add/<int:product_id>/<int:qty>', methods=['POST'])
@login_required
def add_to_cart(product_id, qty):
    # if not current_user.is_authenticated:
    #     return redirect(url_for('users.login'))
    form = AddToCartForm()
    if form.validate_on_submit():
        user_id = current_user.id
        cart = Cart(product_id, qty, user_id)
        db.session.add(cart)
        db.session.commit()
        return redirect(url_for('main.index'))
    return redirect(url_for('main.index'))

##################################################################
############### REMOVE FROM CART #################################
##################################################################

# Page is not displayed, this route removes an item from the cart and redirects to the cart page


@ products.route('/cart/remove/<int:cart_id>', methods=['POST'])
@ login_required
def remove_items(cart_id):
    cart_item = Cart.query.get_or_404(cart_id)
    print(cart_item)
    if cart_item.user_id != current_user.id:
        flash("You cannot update another user's cart", 'danger')
    form = CartForm()
    if form.validate_on_submit():
        db.session.delete(cart_item)
        db.session.commit()
        return redirect(url_for('products.show_cart'))
    return redirect(url_for('main.index'))

##################################################################
############### SHOPPING CART PAGE################################
##################################################################


@ products.route('/cart')
@ login_required
def show_cart():
    form = CartForm()
    items = db.session.query(Cart, Product).join(
        Product).filter(Cart.user_id == current_user.id)
    sum = 0
    for item in items:
        sum = sum + item[1].price
    print(sum)
    cart_empty = is_empty()
    return render_template('shopping_cart.html', items=items, form=form, sum=sum, cart_empty=cart_empty)

##################################################################
############### CLEAR CART #######################################
##################################################################

# Page is not displayed, this route clears the cart and redirects to the index


@ products.route('/cart/remove/clear', methods=['POST'])
@ login_required
def clear_cart():
    form = CartForm()
    if form.validate_on_submit():
        total_cart = Cart.query.filter(Cart.user_id == current_user.id)
        for items in total_cart:
            db.session.delete(items)
            db.session.commit()
        return redirect(url_for('main.index'))
    return redirect(url_for('main.index'))

##################################################################
############### CHECKOUT #########################################
##################################################################

stripe.api_key = app.config['STRIPE_SECRET_KEY']

@ products.route('/cart/checkout', methods=['POST'])
@ login_required
def check_out():
    items = db.session.query(Cart, Product).join(
        Product).filter(Cart.user_id == current_user.id)
    cart_items = []
    for item in items:
        cart_items.append({
        'price_data': {
            'currency': 'usd',
            'product_data': {
            'name': item[1].name,
            },
            'unit_amount': int(item[1].price*100),
        },
        'quantity': 1,
        }
        )
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=cart_items,
        mode='payment',
        success_url=url_for('products.checkout_success',_external=True),
        cancel_url=url_for('products.show_cart', _external=True),
    )

    return redirect(session.url, code=303)

##################################################################
############### CHECKOUT SUCCESS #################################
##################################################################
@ products.route('/cart/checkout/success', methods=['GET'])
@ login_required
def checkout_success():
    total_cart = Cart.query.filter(Cart.user_id == current_user.id)
    for items in total_cart:
        db.session.delete(items)
        db.session.commit()
    cart_empty = is_empty()
    return render_template('success.html',cart_empty=cart_empty)

##################################################################
############### HELPER FUNCTIONS #################################
##################################################################

# Check if the cart is empty to tell the nav bar which cart icon to display


def is_empty():
    if not current_user.is_authenticated:
        return True
    items = db.session.query(Cart, Product).join(
        Product).filter(Cart.user_id == current_user.id)
    if items.count() == 0:
        return True
    else:
        return False

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="apple-touch-icon" sizes="180x180" href="../static/img/apple-touch-icon.png">
    <link rel=" icon" type="image/png" sizes="32x32" href="../static/img/favicon-32x32.png">
    <link rel=" icon" type="image/png" sizes="16x16" href="../static/img/favicon-16x16.png">
    <link rel=" manifest" href="../static/img/site.webmanifest">


    {% block styles %}
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.4/css/intlTelInput.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% endblock %}

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% include 'nav.html' %}

    <div class="container">
        {% include 'message.html' %}

        {% block content %}{% endblock %}
    </div>

    {% include 'footer.html' %}
    {% block scripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/16.0.4/js/intlTelInput.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.min.js"></script>
    {% endblock %}
</body>

</html>

app/templates/index.html
{% extends 'base.html' %}


{% block title %}Jungle Themed Marketplace{% endblock %}

{% block content %}
<div class="container">
    <div class="row row-cols-1  row-cols-md-2 row-cols-lg-3 row-cols-xxl-4 mx-auto g-3 m-3 p-3">
        {% for product in products %}
        <div class="col">
            <div class="card">
                <img src=" {{ product.sm_image_url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.desc }}</p>
                </div>
                <div class="card-footer text-muted">
                    <a href="{{ url_for('products.show_product', product_id=product.id)}}"
                        class="btn btn-orange-moon border-dark text-right">Buy me for only ${{ product.price
                        }}!</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="col-12 text-center mx-auto">
    {% if prev_url %}
    <a href="{{ prev_url }}">Previous Items</a>
    {% endif %}
    {% if next_url %}
    <a href="{{ next_url }}">Next Items</a>
    {% endif %}
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{%block title%}Login {%endblock%}

{% block content %}



<body>
    <div class="container">
        <div class=" row justify-content-center mt-3">
            <!-- Wrapper for login script -->
            <div class="col-md-auto align-content-center">
                <form action="" method="POST">
                    {{ form.hidden_tag() }}
                    <div class="col-md-auto">
                    </div>
                    <div class="card" style="width: 25rem;">
                        <img class="align-self-center" src="../static/img/scamazon_logo_master.png"
                            style="max-width: 200px;">
                        <div class="card-body">
                            <h3 class="card-title">Sign-In</h3>
                            <div class="mb-3">
                                <label for="exampleFormControlInput1" class="form-label fw-bold fs-6">Username</label>
                                {{ form.username(class='form-control', placeholder='Username') }}
                            </div>
                            <div class="mb-3">
                                <label for="exampleFormControlInput1" class="form-label fw-bold fs-6">Password
                                </label>
                                <a href="{{url_for('users.reset_password_request')}}"
                                    class="link-info text-decoration-none float-sm-end">Forgot your
                                    password?</a>
                                {{ form.password(class='form-control', placeholder='Password') }}
                            </div>
                            <div class="d-grid gap-2">
                                <!-- <button class="btn btn-orange-moon border-dark" type="button">Sign-In</button> -->
                                {{ form.submit(class='btn btn-orange-moon border-dark') }}
                            </div>
                            <p class="card-text mt-2">By continuing, you agree to Scamazon's <a href="#"
                                    class="link-info text-decoration-none">Conditions of Use</a> and <a href="#"
                                    class="link-info text-decoration-none">Privacy Notice.</a></p>
                            <div class="form-check">
                                {{ form.remember_me }}
                                Keep me signed in. <a href="#" class="link-dark text-decoration-none">Details</a>
                                </label>
                            </div>
                            <p class="text-divider"><span>NEW TO SCAMAZON?</span></p>






                            <div class="d-grid gap-2 mb-5">
                                <a href="{{ url_for('users.register') }}" class="btn btn-light border-dark"
                                    type="button">
                                    Create your Scamazon account</a>
                            </div>

                            <!-- <div class="container">
                            <br>
                        </div> -->




                        </div>




                        <!-- <ul class="list-group list-group-flush">
                        <li class="list-group-item">An item</li>
                        <li class="list-group-item">A second item</li>
                        <li class="list-group-item">A third item</li>
                    </ul>
                    <div class="card-body">
                        <a href="#" class="card-link">Card link</a>
                        <a href="#" class="card-link">Another link</a>
                    </div> -->
                    </div>
                </form>
            </div>
        </div>
    </div>











</body>


{% endblock content %}

app/templates/message.html
{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible fade show m-3 g-3 p-3" role="alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="../static/img/scamazon_logo_master.png" alt="" width="125" height="50">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('main.index') }}">Home</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.user_update') }}">Update Your Account</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex">
                <ul class="navbar-nav ms-auto">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{  url_for('users.login') }}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </form>
            <form class="d-flex">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        {% if current_user.is_authenticated %}
                        {% if cart_empty %}
                        <a class="nav-link" href="{{  url_for('products.show_cart') }}"><img
                                src="../static/img/cart_button.jpg" alt="" width="100" height="50"></a>
                        {% else %}
                        <a class="nav-link" href="{{  url_for('products.show_cart') }}"><img
                                src="../static/img/cart_w_items.jpg" alt="" width="100" height="50"></a>
                        {% endif %}
                        {% else %}
                        <a class="nav-link" href="{{  url_for('products.show_cart') }}"><img
                                src="../static/img/cart_button.jpg" alt="" width="100" height="50"></a>
                        {% endif %}
                    </li>
                </ul>
            </form>
        </div>
    </div>
</nav>

app/templates/product_view.html
{%extends 'base.html'%}

{%block title%}{{product.name}} {%endblock%}

{% block content %}
<div class="container-fluid mx-auto g-5 m-5 p-5">
    <div class="row">
        <div class="col-sm-12 col-md-6">

            <img src=" {{ product.sm_image_url }}" class="img-fluid" alt="...">

        </div>
        <div class="col-sm-12 col-md-6">
            <h5>{{ product.name }}</h5>
            <p>{{ product.desc }}</p>
            <h1>Buy now for only ${{ product.price }}!!!</h1>



            <form action="{{ url_for('products.add_to_cart', product_id=product.id,qty=1)}}" method="POST">
                {{ form.hidden_tag() }}
                {{form.submit(class='btn btn-orange-moon border-dark', value='Add to Cart')}}
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}


{% block title %}Register!{% endblock %}

{% block content %}
<h1>Reigster your account!</h1>



<form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset>
            {{ form.username.label }}
            {{ form.username(class='form-control', placeholder='username') }}
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {%endfor%}
        </fieldset>
        <fieldset>
            {{ form.password.label }}
            {{ form.password(class='form-control', placeholder='password') }}
        </fieldset>
        <fieldset>
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class='form-control', placeholder='confirm password') }}
        </fieldset>
        <fieldset>
            {{ form.email.label }}
            {{ form.email(class='form-control', placeholder='email') }}
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {%endfor%}
        </fieldset>
        <fieldset>
            {{ form.address.label }}
            {{ form.address(class='form-control', placeholder='address') }}
            {% for error in form.address.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {%endfor%}
        </fieldset>
        <fieldset>
            {{ form.city.label }}
            {{ form.city(class='form-control', placeholder='city') }}
            {% for error in form.city.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {%endfor%}
        </fieldset>
        <fieldset>
            {{ form.state.label }}
            {{ form.state(class='form-control', placeholder='state') }}
            {% for error in form.state.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {%endfor%}
        </fieldset>
        <fieldset>
            {{ form.zip_code.label }}
            {{ form.zip_code(class='form-control', placeholder='zip_code') }}
            {% for error in form.zip_code.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {%endfor%}
        </fieldset>
        {{ form.submit(class='btn btn-orange-moon border-dark') }}
    </div>
</form>

{% endblock %}

app/templates/reset_password.html
{% extends "base.html" %}

{%block title%} Reset Your Password {%endblock%}

{% block content %}
<h1>Reset Your Password</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}<br>
        {% for error in form.password.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password2.label }}<br>
        {{ form.password2(size=32) }}<br>
        {% for error in form.password2.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.submit(class='btn btn-orange-moon border-dark') }}</p>
</form>
{% endblock %}

app/templates/reset_password_request.html
{% extends "base.html" %}

{%block title%}You forgot??? {%endblock%}

{% block content %}
<h1>Reset Password</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.email.label }}<br>
        {{ form.email(size=64) }}<br>
        {% for error in form.email.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.submit(class='btn btn-orange-moon border-dark') }}</p>
</form>
{% endblock %}

app/templates/shopping_cart.html
{% extends 'base.html' %}

{%block title%}Buy Things {%endblock%}

{% block content %}


<div class="container-fluid">
    <div class="row">
        <div class="col-md-9 col-sm-8 content">
            <div class="col-md-12">
                <div class="panel-body">

                    <table class="table">
                        <thead>
                            <tr>
                                <th class="text-center">
                                    <h3>Product</h3>
                                </th>
                                <th>
                                    <h3>Description</h3>
                                </th>
                                <th>
                                    <h3>Price</h3>
                                </th>
                                <th></th>
                            </tr>

                        </thead>
                        <tbody>

                            {% for item in items %}
                            <tr>
                                <td><img src=" {{ item[1].sm_image_url }}" class="img-cart">
                                </td>
                                <td class="align-middle">
                                    <h3>{{item[1].name}}</h3>
                                </td>
                                <td class="align-middle">
                                    <h3>{{item[1].price}}</h3>
                                </td>
                                <td class="align-middle">
                                    <form action="{{ url_for('products.remove_items', cart_id=item[0].id)}}"
                                        method="POST">
                                        {{ form.hidden_tag() }}
                                        {{form.remove_item(class='btn btn-danger', value='Remove from cart')}}
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}



                        </tbody>
                    </table>

                </div>


            </div>
        </div>
        <div class="card mb-3 m-3 g-3 p-3 mx-auto" style="max-width: 500px; border: none">
            <div class="row g-0"></div>

            <div class="col-md-8">
                <div class="card-body">
                    <h4 class="text-center">Total: ${{sum}}</h4>
                    <form action="{{ url_for('products.clear_cart')}}" method="POST">
                        {{ form.hidden_tag() }}
                        {{form.clear_cart(class='btn btn-danger border-dark btn-lg m-3 p-3', value='Clear Cart')}}
                    </form>
                    <form action="{{ url_for('products.check_out')}}" method="POST">
                        {{ form.hidden_tag() }}
                        {{form.check_out(class='btn btn-orange-moon border-dark btn-lg m-3 p-3', value='Check Out')}}
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>

</div>
{%endblock %}

app/templates/success copy.html
{%extends 'base.html'%}

{%block title%}Checkout Successful {%endblock%}

{% block content %}
<div class="container-fluid mx-auto g-5 m-5 p-5">
    <div class="row">
        <div class="col-sm-12 col-md-6">

            <h1>CHECKOUT SUCCESS</h1>

        </div>
 
{% endblock %}

app/templates/success.html
{%extends 'base.html'%}

{%block title%}Checkout Successful {%endblock%}

{% block content %}
<div class="container-fluid mx-auto g-5 m-5 p-5">
    <div class="row">
        <div class="col-sm-12 col-md-6">

            <h1>CHECKOUT SUCCESS</h1>

        </div>

{% endblock %}

app/templates/user_update.html
{% extends 'base.html' %}

{%block title%} Fix your stuff {%endblock%}

{% block content %}
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
<h3>Update user: {{ user.username }}</h3>
<div class="container-fluid">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <fieldset>
                {{ form.username.label }}
                {{ form.username(class='form-control', value=user.username) }}
                {% for error in form.username.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {%endfor%}
            </fieldset>
            <fieldset>
                {{ form.email.label }}
                {{ form.email(class='form-control', value=user.email) }}
                {% for error in form.email.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {%endfor%}
            </fieldset>
            <fieldset>
                {{ form.address.label }}
                {{ form.address(class='form-control', value=user.address) }}
                {% for error in form.address.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {%endfor%}
            </fieldset>
            <fieldset>
                {{ form.city.label }}
                {{ form.city(class='form-control', value=user.city) }}
                {% for error in form.city.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {%endfor%}
            </fieldset>
            <fieldset>
                {{ form.state.label }}
                {{ form.state(class='form-control', value=user.state) }}
                {% for error in form.state.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {%endfor%}
            </fieldset>
            <fieldset>
                {{ form.zip_code.label }}
                {{ form.zip_code(class='form-control', value=user.zip_code) }}
                {% for error in form.zip_code.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {%endfor%}
            </fieldset>
            {{ form.submit(class='btn btn-orange-moon border-dark') }}
        </div>
    </form>
</div>

{% endblock content %}